### ISSUE TITLE
This is only a hide method remover, smh you guys are retarded

### ISSUE THREAD

**Issue by ghost** [CursedSheep/Atomic-Deobfuscator#2]
This is only a hide method remover, smh you guys are retarded

Join the discord server to buy the best C# Obfuscator 

https://discord.gg/Bwk5c8R

**Comment by Jomtek** [comment]
![image](https://user-images.githubusercontent.com/26415769/84150907-d6791d80-aa62-11ea-9599-190d86104d3a.png)
![image](https://user-images.githubusercontent.com/26415769/84150923-db3dd180-aa62-11ea-8785-3f2b4c3123aa.png)
Fuck you
